import test from 'node:test';import assert from 'node:assert/strict';import {createMetadataServer} from '../server.js';
const id='M7lc1UVf-VE';
async function setup(t,options={}){let calls=0;const server=createMetadataServer({key:'test-secret',channelId:'nick-channel',fetchImpl:async()=>{calls++;return{ok:true,json:async()=>({items:[{id,snippet:{title:'Nick video',channelId:'nick-channel',publishedAt:'2020-03-02T18:00:00Z'},status:{privacyStatus:'public',embeddable:true}}]})};},...options});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return{url:`http://127.0.0.1:${server.address().port}`,calls:()=>calls};}
test('returns public Nick video date and caches lookup',async t=>{const s=await setup(t);for(let i=0;i<2;i++){const r=await fetch(s.url+'/video-metadata?id='+id,{headers:{Origin:'https://nickdiramio.com'}});assert.equal(r.status,200);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://nickdiramio.com');assert.deepEqual(await r.json(),{videoId:id,title:'Nick video',publishedAt:'2020-03-02T18:00:00.000Z'});}assert.equal(s.calls(),1);});
test('invalid IDs, origins and methods cannot call YouTube',async t=>{const s=await setup(t);assert.equal((await fetch(s.url+'/video-metadata?id=no')).status,400);assert.equal((await fetch(s.url+'/video-metadata?id='+id,{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await fetch(s.url+'/video-metadata?id='+id,{method:'POST'})).status,405);assert.equal(s.calls(),0);});
test('other channels and private videos are not returned',async t=>{for(const channelId of ['other','nick-channel']){const s=await setup(t,{fetchImpl:async()=>({ok:true,json:async()=>({items:[{id,snippet:{channelId,title:'Private',publishedAt:'2020-03-02'},status:{privacyStatus:channelId==='other'?'public':'private'}}]})})});assert.equal((await fetch(s.url+'/video-metadata?id='+id)).status,404);}});
test('upstream errors never expose credentials',async t=>{const s=await setup(t,{fetchImpl:async()=>{throw new Error('test-secret');}});const r=await fetch(s.url+'/video-metadata?id='+id);assert.equal(r.status,502);assert(!(await r.text()).includes('test-secret'));});
test('global budget bounds uncached requests',async t=>{const s=await setup(t,{maxLookups:1});await fetch(s.url+'/video-metadata?id='+id);assert.equal((await fetch(s.url+'/video-metadata?id=abcdefghijk')).status,429);assert.equal(s.calls(),1);});
test('concurrent requests coalesce and cache expires',async t=>{let time=0;const s=await setup(t,{now:()=>time});await Promise.all([fetch(s.url+'/video-metadata?id='+id),fetch(s.url+'/video-metadata?id='+id)]);assert.equal(s.calls(),1);time=86400001;await fetch(s.url+'/video-metadata?id='+id);assert.equal(s.calls(),2);});
